DROP TABLE TEMP_EMP;
DROP TABLE EMPLEADOS;
DROP TABLE TRAMO_REAJUSTE_ANUAL;
DROP TABLE DETALLE_REAJUSTE_ANUAL;
DROP TABLE TRAMO_ASIG_JEFE;
DROP TABLE TRAMO_DESCTO_SINDICATO;
DROP TABLE HABER_CALC_SALARIO;
DROP TABLE RESUMEN_GASTO_REAJ_POR_DEPTO;
DROP TABLE ERROR_PROCESO;
DROP SEQUENCE SEQ_ERROR_PROC;

CREATE SEQUENCE SEQ_ERROR_PROC;

CREATE TABLE temp_emp
AS SELECT * FROM employees;

CREATE TABLE empleados
AS SELECT * FROM employees;

CREATE TABLE TRAMO_ASIG_JEFE
(tramo_inf_aj NUMBER(2) NOT NULL,
 tramo_sup_aj NUMBER(2) NOT NULL,
 porc_asig_jefe NUMBER(2) NOT NULL,
 CONSTRAINT PK_TRAMO_ASIG_JEFE PRIMARY KEY(tramo_inf_aj,tramo_sup_aj));

 CREATE TABLE TRAMO_DESCTO_SINDICATO
(nro_tramo_ds  NUMBER(2) NOT NULL,
 tramo_inf_ds NUMBER(8) NOT NULL,
 tramo_sup_ds NUMBER(8) NOT NULL,
 porc_ds NUMBER(4,3) NOT NULL,
CONSTRAINT PK_TRAMO_DESCTO_JEFE PRIMARY KEY(nro_tramo_ds));

CREATE TABLE DETALLE_REAJUSTE_ANUAL
(anno_reajuste_ra NUMBER(4) NOT NULL,
 id_empleado NUMBER(8) NOT NULL,
 id_departamento NUMBER(4),
 salario_sin_reajuste NUMBER(8) NOT NULL,
 salario_reajustado NUMBER(8) NOT NULL,
CONSTRAINT PK_DET_REAJ_ANUAL PRIMARY KEY(anno_reajuste_ra,id_empleado));
 
 CREATE TABLE HABER_CALC_SALARIO
 (id_empleado NUMBER(3) NOT NULL,
  anno_mes_proc NUMBER(6) NOT NULL,
  valor_sldo_base NUMBER(8) NOT NULL,
  valor_comision NUMBER(5) NOT NULL,
  valor_comision_jefe NUMBER(5) NOT NULL,
  valor_colacion NUMBER(5) NOT NULL,
  valor_movil NUMBER(8) NOT NULL,
  valor_descto_sindicato NUMBER(8) NOT NULL,
  valor_alc_liquido NUMBER(8) NOT NULL,
  CONSTRAINT PK_HABER_CAL_SALARIO PRIMARY KEY(id_empleado,anno_mes_proc));
 
CREATE TABLE RESUMEN_GASTO_REAJ_POR_DEPTO
 (anno_reajuste NUMBER(4) NOT NULL,
  nro_depto NUMBER(4) NOT NULL,
  valor_total_sal_sinreaj NUMBER(15) NOT NULL,
  valor_total_sal_conreaj NUMBER(15) NOT NULL,
  CONSTRAINT PK_RES_GASTO_REAJ_POR_DEPTO PRIMARY KEY(anno_reajuste,nro_depto));

CREATE TABLE TRAMO_REAJUSTE_ANUAL
(anno_tramo_ra NUMBER(4) NOT NULL,
 nro_tramo_ra NUMBER(1) NOT NULL,
 tramo_inf_ra NUMBER(6) NOT NULL,
 tramo_sup_ra NUMBER(6) NOT NULL,
 porc_reajuste_ra NUMBER(4,3) NOT NULL,
CONSTRAINT PK_TRAMO_REAJUSTE_ANUAL PRIMARY KEY(anno_tramo_ra,nro_tramo_ra));

CREATE TABLE ERROR_PROCESO
(sec_error NUMBER(3) NOT NULL,
 rutina_error VARCHAR2(100) NOT NULL,
 mensaje_error VARCHAR2(250) NOT NULL,
 CONSTRAINT PK_ERROR_PROCESO PRIMARY KEY(sec_error));

INSERT INTO TRAMO_ASIG_JEFE VALUES(1,5,5);
INSERT INTO TRAMO_ASIG_JEFE VALUES(5,7,5);
INSERT INTO TRAMO_ASIG_JEFE VALUES(8,10,7);
INSERT INTO TRAMO_ASIG_JEFE VALUES(11,15,9);
INSERT INTO TRAMO_ASIG_JEFE VALUES(16,20,10);

INSERT INTO TRAMO_DESCTO_SINDICATO VALUES(1,1000,3000,0.02);
INSERT INTO TRAMO_DESCTO_SINDICATO VALUES(2,3001,6000,0.025);
INSERT INTO TRAMO_DESCTO_SINDICATO VALUES(3,8000,10000,0.035);
INSERT INTO TRAMO_DESCTO_SINDICATO VALUES(4,10001,30000,0.045);
  
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE)-1,1,1,1000,0.20);
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE)-1,2,1001,3000,0.16);
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE)-1,3,3001,7000,0.10);
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE)-1,4,7001,10000,0.8);
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE)-1,5,10001,20000,0.05);
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE)-1,6,20001,50000,0.03);
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE),1,1,3000,0.12);
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE),2,3001,7000,0.10);
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE),3,7001,12000,0.07);
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE),4,12001,20000,0.05);
INSERT INTO TRAMO_REAJUSTE_ANUAL VALUES(EXTRACT(YEAR FROM SYSDATE),5,20001,50000,0.02);
COMMIT;

